name: AdvancedRules
author: CaptainDuck
main: AdvancedRules\Main
version: 1.0.0
api: [2.0.0]
commands:
    rules:
        usage: "/rules <player, premium, staff, notes>"
        description: "Shows rules for specified group"
        permission: ar.rules
permissions:
    ar.rules:
        default: true
